CREATE TABLE personmessage (
    id       NUMBER(19)   PRIMARY KEY NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    message  VARCHAR(255) NOT NULL
);

CREATE SEQUENCE personmessage_seq MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
